import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from 'next/font/google';
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/UI/header/header";
import Footer from "@/components/UI/footer/footer";
import clsx from "clsx";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const stackSansNotch = localFont({
  src: './font/StackSansNotch/StackSansNotch-Regular.ttf', 
  variable: '--font-stack-sans-notch',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'], 
  weight: ['400', '500', '700'],   
  variable: '--font-montserrat',  
  display: 'swap',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={clsx(montserrat.variable, stackSansNotch.variable)}>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=call" />
      </head>
      <body
        className="font-sans"
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
